config/routes.rb
Rails.application.routes.draw do
  root 'application#home', as: 'home'

  resources :player
  post 'player/create', to: 'player#create', as: 'create_player'

  get 'roulette/increase' => 'roulette#increase', as: 'roulette_increase_balance'

  get 'roulette/new_round' => 'roulette#new_round', as: 'roulette_new_round'

end

app/models/player.rb
class Player < ApplicationRecord

	has_many :plays, :dependent => :delete_all


	validates :name, presence: true, uniqueness: true

	before_create :set_initial


	def self.set_balance(jugador, ganancia)
		jugador.money = jugador.money + ganancia
		jugador.save
	end

	def self.increase_balance(jugador, extra)
		jugador.money = jugador.money + extra
		jugador.save
	end


	def set_initial
	    self.money = 10000
	    self.active = true
  	end

end

app/controllers/player_controller.rb
class PlayerController < ApplicationController

	respond_to :js, :html, :json

	def index
		@players = Player.all
		@ruleta = Roulette.first
	end

	def new
		@player = Player.new
		respond_to do |format|
	      format.html
	      format.js
	    end
	end

	def create
		@player = Player.new(params[:player].permit(:name))
		respond_to do |format|
	      if @player.save
	      	flash[:success] = 'Se ha creado jugador'
	        #format.js { render "create" }
	        format.html { redirect_to home_path(), notice: 'Player was successfully created. Will appear in next round'}#, notice: 'Task was successfully created.' }
	        #format.json { render json: @player, status: :created, location: @player }
	      else
	        #format.html { redirect_to boards_project_path(@task.project_id), status: :unprocessable_entity }
	        format.js { render "error"}
	        format.json { render json: @player.errors, status: :unprocessable_entity }
	      end
	    end
	end


	def update
	  @player = Player.find params[:id]
	  respond_to do |format|
	    if @player.update_attributes(params[:player].permit(:name, :money, :active))
	      format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
	      format.json { respond_with_bip(@player) }
	    else
	      format.html { render :action => "edit" }
	      puts "UPDATEED"
	      format.js { render "error"}
	      #format.json { render json: @player.errors, status: :unprocessable_entity }
	    end
	  end
	end

	def destroy
	    @player = Player.find(params[:id])
	    @player.destroy
	    respond_to do |format|
	      	flash[:success] = 'Se ha creado jugador'
	        #format.js { render "create" }
	        format.html { redirect_to home_path(), notice: 'Player was Deleted'}#, notice: 'Task was successfully created.' }
	    end
	end 

end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/player/_form.html.erb
<div id="modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <%= form_for @player, url: create_player_path, html: { method: :post }, remote: true do |f| %>
        <div class="modal-body">
          <div class="form-group">
            <%= f.label :name, class: "control-label col-sm-2", style: "font-size: 20px;" %>
            <%= f.text_field :name, class: "form-control input-lg" %>
          </div>
          
          <div class="form-group">
            <%= f.label :money, 'Initial Balance: $10.000', style: "font-size: 20px; width:80%;" %>
          </div>
        </div>


        <div class="modal-footer">
          <%= f.submit class: "btn btn-primary btn-lg btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/player/create.js.erb
$('#modal').modal('hide');
$('.in').remove();
$('#modal').remove();

app/views/player/error.js.erb
alert("Usuario ya existe! Probar con otro");

app/views/player/index.html.erb
<table class="table players">
    <thead>
      <tr>
        <th>Name</th>
        <th>Money</th>
        <th>Active</th>
        <th>Active</th>
      </tr>
    </thead>
    <tbody>
    	<% @players.each do |a| %>
	      <tr class="success">
	        <td >	<%= best_in_place a, :name, :as => :input %>	</td>
	        <td>	<%= best_in_place a, :money, :as => :input %>	</td>
	        <td class="check">	<%= best_in_place a, :active, as: :checkbox, collection: {false: "Nope", true: "Yep"} %>	</td>
	        <td><%= link_to 'Destroy', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
    </tbody>
</table>

<p>Last Round: <%= @ruleta.last_round.strftime("%Y-%m-%d %H:%M:%S") %></p>
<p>Next Round: <%= (@ruleta.last_round+3.minutes).strftime("%Y-%m-%d %H:%M:%S") %></p>

<%= link_to 'Home', home_path, :html => { :class => "btn" } %>

app/views/player/new.html.erb
<%- model_class = Player -%>
<%= render :partial => 'form' %>

app/views/player/new.js.erb
$('<%= j render "form", title: "Crear Jugador" %>').modal();

$(window).on('shown.bs.modal', function() {

	$(window).on('hidden.bs.modal', function() { 
		$('#modal').modal('hide');
		$('.in').remove();
		$('#modal').remove();
 	});

});