config/routes.rb
Rails.application.routes.draw do
  root 'application#home', as: 'home'

  resources :player
  post 'player/create', to: 'player#create', as: 'create_player'

  get 'roulette/increase' => 'roulette#increase', as: 'roulette_increase_balance'

  get 'roulette/new_round' => 'roulette#new_round', as: 'roulette_new_round'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  def home
  	@ruleta = Roulette.first
  	@rondas = @ruleta.rounds.length
  	@ultima_ronda = Round.last
  	if !@ultima_ronda || Player.where(active:true).length == 0
  		@jugadores = Player.where(active:true).sort_by{ |t| t.money }.reverse 
  		render 'empty'
  	else
  		@apuestas = Play.where(round_id:@ultima_ronda.id)
	  	#Consultamos a API si lloverá durante los próximos 7 días
	  	habra_lluvia = Weather2.forecast_rain
	  	@color = @ultima_ronda.last_color
		#Arreglo json con las predicciones por dia. Atributos: code,date,day,text
		@clima = Weather2.get_forecast
		@pronostico = ""
		if habra_lluvia
			@pronostico = "Se pronostica lluvia dentro de los próximos 7 días. Apuestas conservadoras."
		else
			@pronostico = "No se anuncian chubascos durante la próxima semana."
		end
  	end

  end


  private
  def set_color
  	aleatorio = rand(1..100)
  	if aleatorio <= 2
  		color = 'green'
  	elsif aleatorio <= 51
  		color = 'red'
  	else
  		color = 'black'
  	end
  	return color
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/empty.html.erb
<h1 class="hola">Cree Jugadores o Espere a que se ejecute la primera ronda del juego</h1>

<div class="game-container">
	<div class="players-container">

		<p>Jugadores Activos</p>

		<table class="table game">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>Balance</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @jugadores.each do |a| %>
			      <tr class="success">
			        <td>	<%=a.name%>	</td>
			        <td>	<%=a.money%>	</td>
			      </tr>
			    <% end %>
		    </tbody>
		</table>

	</div>

		 <%= link_to 'Add Player', new_player_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal', 'data-backdrop' => "false", 'data-keyboard' => "false"}  %>  

	<div class="action-container">
         <%= link_to 'Edit Players', player_index_path  %>   
	</div>

	
            
</div>

app/views/application/home.html.erb
<h1 class="hola">Hello, Nnodes!</h1>


<div class="game-container">
	<div class="players-container">

		<p>Resultado última ronda: <%=@color.to_s%></p>
		<p># Ronda: <%=@rondas%></p>

		<p>Pronóstico del Tiempo: <%=@pronostico%></p>

		<p>Last Round: <%= @ruleta.last_round.strftime("%Y-%m-%d %H:%M:%S") %></p>
		<p>Next Round: <%= (@ruleta.last_round+3.minutes).strftime("%Y-%m-%d %H:%M:%S") %></p>

		<table class="table game">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th>Balance</th>
		        <th>Last Bet</th>
		        <th>Last Turn Earnings</th>
		      </tr>
		    </thead>
		    <tbody>
		    	<% @apuestas.each do |a| %>
			      <tr class="success">
			        <td>	<%=a.player.name%>	</td>
			        <td>	<%=a.player.money%>	</td>
			        <td>	<%=a.color%>	</td>
			       	<td>	<%=a.getResult(@color)%>	</td>
			      </tr>
			    <% end %>
		    </tbody>
		</table>

	</div>

		 <%= link_to 'Add Player', new_player_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal', 'data-backdrop' => "false", 'data-keyboard' => "false"}  %>  

	<div class="action-container">
         <%= link_to 'Edit Players', player_index_path  %>   
	</div>

	
            
</div>



<div class="weather-container">
	<div class="forecast-container">

		<p>Weather Forecast, Upcoming 7 Days</p>

		<table class="table weather">
		    <thead>
		      <tr>
		        <th>Day</th>
		        <th>Forecast</th>
		      </tr>
		    </thead>
		    <tbody>
			    	<% @clima[0..6].each do |c| %>
				      <tr class="success">
				        <td>	<%=c.day%>	</td>
				        <td>	<%=c.text%>	</td>
				      </tr>
				    <% end %>
		    </tbody>
		</table>

	</div>

            
</div>